import { Company, Candidate, Job, Application } from '../types/jobs';

// الولايات الجزائرية
export const algerianStates = [
  'الجزائر', 'وهران', 'قسنطينة', 'عنابة', 'بجاية', 'سطيف', 'تلمسان', 'ورقلة',
  'بشار', 'باتنة', 'سكيكدة', 'جيجل', 'مستغانم', 'البليدة', 'تيزي وزو',
  'الشلف', 'تيارت', 'بسكرة', 'المدية', 'الأغواط'
];

export const mockCompanies: Company[] = [
  {
    id: 'comp-1',
    email: 'hr@sonatrach.dz',
    name: 'سوناطراك',
    type: 'company',
    description: 'شركة جزائرية وطنية رائدة في مجال النفط والغاز',
    location: 'الجزائر',
    industry: 'النفط والغاز',
    website: 'www.sonatrach.com',
    employeeCount: '+50000',
    createdAt: new Date('2024-01-01'),
  },
  {
    id: 'comp-2',
    email: 'contact@condor.dz',
    name: 'كوندور الكترونيكس',
    type: 'company',
    description: 'شركة جزائرية رائدة في تصنيع الإلكترونيات',
    location: 'برج بوعريريج',
    industry: 'التكنولوجيا والإلكترونيات',
    website: 'www.condor.dz',
    employeeCount: '1000-5000',
    createdAt: new Date('2024-01-15'),
  },
  {
    id: 'comp-3',
    email: 'jobs@algerieTelecom.dz',
    name: 'اتصالات الجزائر',
    type: 'company',
    description: 'المشغل الرئيسي للاتصالات في الجزائر',
    location: 'الجزائر',
    industry: 'الاتصالات',
    website: 'www.algerietelecom.dz',
    employeeCount: '10000-50000',
    createdAt: new Date('2024-02-01'),
  },
  {
    id: 'comp-4',
    email: 'hr@naftal.dz',
    name: 'نفطال',
    type: 'company',
    description: 'شركة وطنية لتوزيع المنتجات البترولية',
    location: 'الجزائر',
    industry: 'الطاقة',
    employeeCount: '5000-10000',
    createdAt: new Date('2024-02-10'),
  },
];

export const mockCandidates: Candidate[] = [
  {
    id: 'cand-1',
    email: 'ahmed.benali@gmail.com',
    name: 'أحمد بن علي',
    type: 'candidate',
    phone: '0555123456',
    location: 'الجزائر',
    title: 'مطور ويب Full Stack',
    bio: 'مطور ويب محترف مع خبرة 5 سنوات في React و Node.js',
    skills: ['React', 'Node.js', 'TypeScript', 'MongoDB', 'Arabic', 'French', 'English'],
    experience: '5 سنوات في تطوير الويب',
    education: 'ماجستير في علوم الحاسوب - جامعة هواري بومدين',
    createdAt: new Date('2024-03-01'),
  },
  {
    id: 'cand-2',
    email: 'fatima.sarah@gmail.com',
    name: 'فاطمة سارة',
    type: 'candidate',
    phone: '0661234567',
    location: 'وهران',
    title: 'مهندسة مدنية',
    bio: 'مهندسة مدنية متخصصة في إدارة المشاريع',
    skills: ['AutoCAD', 'إدارة المشاريع', 'التخطيط العمراني', 'French', 'Arabic'],
    experience: '3 سنوات في الهندسة المدنية',
    education: 'مهندسة دولة - المدرسة الوطنية للأشغال العمومية',
    createdAt: new Date('2024-03-15'),
  },
];

export const mockJobs: Job[] = [
  {
    id: 'job-1',
    companyId: 'comp-1',
    companyName: 'سوناطراك',
    title: 'مهندس بترول - Petroleum Engineer',
    description: 'نبحث عن مهندس بترول ذو خبرة للانضمام إلى فريقنا في حقول النفط',
    location: 'حاسي مسعود، ورقلة',
    type: 'full-time',
    salary: '120,000 - 180,000 دج',
    requirements: [
      'شهادة مهندس في البترول أو ما يعادلها',
      'خبرة لا تقل عن 3 سنوات في المجال',
      'إتقان اللغتين العربية والإنجليزية',
      'القدرة على العمل الميداني',
    ],
    responsibilities: [
      'الإشراف على عمليات الحفر والاستخراج',
      'تحليل البيانات الجيولوجية',
      'إعداد التقارير الفنية',
      'ضمان السلامة والجودة',
    ],
    status: 'active',
    postedAt: new Date('2024-11-01'),
    applicants: 45,
  },
  {
    id: 'job-2',
    companyId: 'comp-2',
    companyName: 'كوندور الكترونيكس',
    title: 'مطور تطبيقات موبايل - Mobile Developer',
    description: 'فرصة رائعة للانضمام إلى فريق التطوير في شركة كوندور',
    location: 'برج بوعريريج',
    type: 'full-time',
    salary: '80,000 - 120,000 دج',
    requirements: [
      'خبرة في تطوير تطبيقات Android/iOS',
      'معرفة بـ React Native أو Flutter',
      'شهادة جامعية في الإعلام الآلي',
      'حس إبداعي ومهارات حل المشاكل',
    ],
    responsibilities: [
      'تطوير تطبيقات موبايل عالية الجودة',
      'العمل ضمن فريق Agile',
      'صيانة وتحديث التطبيقات الحالية',
      'التعاون مع المصممين والمطورين',
    ],
    status: 'active',
    postedAt: new Date('2024-11-05'),
    applicants: 67,
  },
  {
    id: 'job-3',
    companyId: 'comp-3',
    companyName: 'اتصالات الجزائر',
    title: 'مسؤول خدمة الزبائن - Customer Service',
    description: 'انضم إلى فريق خدمة العملاء في اتصالات الجزائر',
    location: 'الجزائر العاصمة',
    type: 'full-time',
    salary: '50,000 - 70,000 دج',
    requirements: [
      'مستوى ثانوي أو جامعي',
      'مهارات تواصل ممتازة',
      'إتقان اللغة العربية والفرنسية',
      'خبرة في خدمة العملاء (مفضل)',
    ],
    responsibilities: [
      'استقبال والرد على استفسارات العملاء',
      'حل المشاكل التقنية البسيطة',
      'تقديم معلومات عن المنتجات والخدمات',
      'الحفاظ على رضا العملاء',
    ],
    status: 'active',
    postedAt: new Date('2024-11-08'),
    applicants: 123,
  },
  {
    id: 'job-4',
    companyId: 'comp-2',
    companyName: 'كوندور الكترونيكس',
    title: 'مصمم جرافيك - Graphic Designer',
    description: 'نبحث عن مصمم جرافيك مبدع للعمل على مشاريع متنوعة',
    location: 'برج بوعريريج',
    type: 'full-time',
    salary: '60,000 - 90,000 دج',
    requirements: [
      'خبرة في Adobe Creative Suite',
      'معرفة بالتصميم الرقمي والطباعة',
      'portfolio قوي',
      'إبداع وحس فني عالي',
    ],
    responsibilities: [
      'تصميم مواد تسويقية وإعلانية',
      'إنشاء هوية بصرية للمنتجات',
      'تصميم واجهات المستخدم',
      'التعاون مع فريق التسويق',
    ],
    status: 'active',
    postedAt: new Date('2024-11-10'),
    applicants: 34,
  },
  {
    id: 'job-5',
    companyId: 'comp-4',
    companyName: 'نفطال',
    title: 'محاسب - Accountant',
    description: 'فرصة عمل في قسم المحاسبة في شركة نفطال',
    location: 'الجزائر العاصمة',
    type: 'full-time',
    salary: '70,000 - 100,000 دج',
    requirements: [
      'شهادة في المحاسبة أو المالية',
      'خبرة 2-3 سنوات في المجال',
      'إتقان برامج المحاسبة',
      'دقة والتزام بالمواعيد',
    ],
    responsibilities: [
      'إعداد التقارير المالية',
      'إدارة الفواتير والمدفوع��ت',
      'المراجعة والتدقيق المالي',
      'التعاون مع الأقسام الأخرى',
    ],
    status: 'active',
    postedAt: new Date('2024-11-11'),
    applicants: 28,
  },
  {
    id: 'job-6',
    companyId: 'comp-3',
    companyName: 'اتصالات الجزائر',
    title: 'تقني شبكات - Network Technician',
    description: 'تقني للعمل على صيانة وتطوير شبكات الاتصالات',
    location: 'قسنطينة',
    type: 'full-time',
    salary: '55,000 - 80,000 دج',
    requirements: [
      'شهادة تقني سامي في الشبكات',
      'معرفة بأنظمة Cisco وHuawei',
      'استعداد للعمل الميداني',
      'رخصة سياقة',
    ],
    responsibilities: [
      'صيانة معدات الشبكة',
      'تشخيص وحل المشاكل التقنية',
      'تركيب معدات جديدة',
      'إعداد تقارير فنية',
    ],
    status: 'active',
    postedAt: new Date('2024-11-09'),
    applicants: 52,
  },
];

export const mockApplications: Application[] = [
  {
    id: 'app-1',
    jobId: 'job-2',
    candidateId: 'cand-1',
    candidateName: 'أحمد بن علي',
    candidateEmail: 'ahmed.benali@gmail.com',
    coverLetter: 'لدي خبرة كبيرة في تطوير تطبيقات الموبايل باستخدام React Native وأنا متحمس للانضمام إلى فريقكم.',
    status: 'pending',
    appliedAt: new Date('2024-11-06'),
  },
  {
    id: 'app-2',
    jobId: 'job-1',
    candidateId: 'cand-2',
    candidateName: 'فاطمة سارة',
    candidateEmail: 'fatima.sarah@gmail.com',
    status: 'reviewed',
    appliedAt: new Date('2024-11-02'),
  },
];
