import { User, Company, Candidate, Job, Application } from '../types';

export const mockUsers: User[] = [
  {
    id: 'user-1',
    email: 'demo.company@example.com',
    type: 'company',
    name: 'TechCorp Inc.',
    createdAt: new Date('2024-01-15'),
  },
  {
    id: 'user-2',
    email: 'demo.candidate@example.com',
    type: 'candidate',
    name: 'John Doe',
    createdAt: new Date('2024-02-20'),
  },
  {
    id: 'user-3',
    email: 'innovate@example.com',
    type: 'company',
    name: 'Innovate Solutions',
    createdAt: new Date('2024-01-10'),
  },
  {
    id: 'user-4',
    email: 'jane.smith@example.com',
    type: 'candidate',
    name: 'Jane Smith',
    createdAt: new Date('2024-03-01'),
  },
];

export const mockCompanies: Company[] = [
  {
    id: 'company-1',
    userId: 'user-1',
    companyName: 'TechCorp Inc.',
    description: 'Leading technology solutions provider specializing in cloud infrastructure and AI.',
    website: 'https://techcorp.example.com',
    location: 'San Francisco, CA',
    size: '500-1000',
  },
  {
    id: 'company-2',
    userId: 'user-3',
    companyName: 'Innovate Solutions',
    description: 'Digital transformation consultancy helping businesses modernize their operations.',
    website: 'https://innovate.example.com',
    location: 'New York, NY',
    size: '100-500',
  },
];

export const mockCandidates: Candidate[] = [
  {
    id: 'candidate-1',
    userId: 'user-2',
    fullName: 'John Doe',
    phone: '+1-555-0123',
    location: 'San Francisco, CA',
    title: 'Senior Software Engineer',
    summary: 'Experienced software engineer with 8+ years in full-stack development, specializing in React, Node.js, and cloud technologies.',
    cvFileName: 'john_doe_resume.pdf',
    skills: ['React', 'Node.js', 'TypeScript', 'AWS', 'PostgreSQL', 'Docker', 'Kubernetes'],
    experience: [
      {
        id: 'exp-1',
        company: 'Tech Solutions Inc.',
        position: 'Senior Software Engineer',
        startDate: '2020-03',
        current: true,
        description: 'Lead development of microservices architecture serving 1M+ users. Mentored junior developers and conducted code reviews.',
      },
      {
        id: 'exp-2',
        company: 'StartupXYZ',
        position: 'Full Stack Developer',
        startDate: '2017-06',
        endDate: '2020-02',
        current: false,
        description: 'Built and maintained web applications using React and Node.js. Implemented CI/CD pipelines and automated testing.',
      },
    ],
    education: [
      {
        id: 'edu-1',
        institution: 'University of California, Berkeley',
        degree: 'Bachelor of Science',
        field: 'Computer Science',
        startDate: '2013-09',
        endDate: '2017-05',
        current: false,
      },
    ],
  },
  {
    id: 'candidate-2',
    userId: 'user-4',
    fullName: 'Jane Smith',
    phone: '+1-555-0456',
    location: 'New York, NY',
    title: 'Product Manager',
    summary: 'Strategic product manager with 6+ years experience launching successful B2B SaaS products.',
    cvFileName: 'jane_smith_resume.pdf',
    skills: ['Product Strategy', 'Agile', 'User Research', 'Data Analysis', 'Roadmapping', 'Stakeholder Management'],
    experience: [
      {
        id: 'exp-3',
        company: 'Enterprise Software Co.',
        position: 'Senior Product Manager',
        startDate: '2021-01',
        current: true,
        description: 'Leading product development for enterprise CRM platform. Increased user engagement by 45% through data-driven feature prioritization.',
      },
      {
        id: 'exp-4',
        company: 'Growth Startup',
        position: 'Product Manager',
        startDate: '2018-07',
        endDate: '2020-12',
        current: false,
        description: 'Managed product lifecycle from conception to launch. Collaborated with engineering and design teams to deliver high-quality products.',
      },
    ],
    education: [
      {
        id: 'edu-2',
        institution: 'Columbia University',
        degree: 'MBA',
        field: 'Business Administration',
        startDate: '2016-09',
        endDate: '2018-05',
        current: false,
      },
      {
        id: 'edu-3',
        institution: 'NYU',
        degree: 'Bachelor of Arts',
        field: 'Economics',
        startDate: '2012-09',
        endDate: '2016-05',
        current: false,
      },
    ],
  },
];

export const mockJobs: Job[] = [
  {
    id: 'job-1',
    companyId: 'company-1',
    title: 'Senior Full Stack Engineer',
    description: 'We are looking for an experienced Full Stack Engineer to join our growing team. You will work on building scalable web applications using modern technologies and best practices.',
    requirements: [
      '5+ years of professional software development experience',
      'Strong proficiency in React and Node.js',
      'Experience with TypeScript',
      'Knowledge of cloud platforms (AWS, GCP, or Azure)',
      'Understanding of database design and optimization',
    ],
    qualifications: [
      'Bachelor\'s degree in Computer Science or related field',
      'Experience with microservices architecture',
      'Strong problem-solving and communication skills',
      'Ability to work in an agile environment',
    ],
    responsibilities: [
      'Design and implement scalable backend services',
      'Develop responsive user interfaces',
      'Collaborate with product and design teams',
      'Mentor junior developers',
      'Participate in code reviews and technical discussions',
    ],
    salaryMin: 140000,
    salaryMax: 180000,
    salaryCurrency: 'USD',
    location: 'San Francisco, CA',
    type: 'full-time',
    remote: true,
    experienceLevel: 'senior',
    postedDate: new Date('2024-10-15'),
    status: 'active',
  },
  {
    id: 'job-2',
    companyId: 'company-1',
    title: 'DevOps Engineer',
    description: 'Join our infrastructure team to build and maintain our cloud infrastructure. You will work with cutting-edge technologies to ensure high availability and performance.',
    requirements: [
      '3+ years of DevOps or infrastructure experience',
      'Strong knowledge of Docker and Kubernetes',
      'Experience with AWS or similar cloud platforms',
      'Proficiency in scripting (Python, Bash)',
      'Understanding of CI/CD pipelines',
    ],
    qualifications: [
      'Experience with infrastructure as code (Terraform, CloudFormation)',
      'Knowledge of monitoring and logging tools',
      'Strong automation mindset',
    ],
    responsibilities: [
      'Manage and optimize cloud infrastructure',
      'Implement CI/CD pipelines',
      'Monitor system performance and reliability',
      'Automate deployment processes',
      'Troubleshoot production issues',
    ],
    salaryMin: 120000,
    salaryMax: 160000,
    salaryCurrency: 'USD',
    location: 'San Francisco, CA',
    type: 'full-time',
    remote: true,
    experienceLevel: 'mid',
    postedDate: new Date('2024-10-20'),
    status: 'active',
  },
  {
    id: 'job-3',
    companyId: 'company-2',
    title: 'Product Manager',
    description: 'We are seeking a talented Product Manager to drive the strategy and execution of our B2B SaaS products.',
    requirements: [
      '4+ years of product management experience',
      'Experience with B2B SaaS products',
      'Strong analytical and data-driven decision making',
      'Excellent communication and stakeholder management',
      'Understanding of agile methodologies',
    ],
    qualifications: [
      'MBA or equivalent experience',
      'Technical background is a plus',
      'Experience with product analytics tools',
    ],
    responsibilities: [
      'Define product vision and strategy',
      'Collaborate with engineering and design teams',
      'Conduct user research and gather feedback',
      'Prioritize features and manage product roadmap',
      'Analyze metrics and iterate on features',
    ],
    salaryMin: 130000,
    salaryMax: 170000,
    salaryCurrency: 'USD',
    location: 'New York, NY',
    type: 'full-time',
    remote: false,
    experienceLevel: 'senior',
    postedDate: new Date('2024-11-01'),
    status: 'active',
  },
  {
    id: 'job-4',
    companyId: 'company-2',
    title: 'Frontend Developer',
    description: 'Looking for a skilled Frontend Developer to create beautiful and performant user interfaces.',
    requirements: [
      '3+ years of frontend development experience',
      'Expert knowledge of React and modern JavaScript',
      'Strong CSS and responsive design skills',
      'Experience with state management (Redux, Context API)',
    ],
    qualifications: [
      'Bachelor\'s degree or equivalent experience',
      'Experience with TypeScript',
      'Knowledge of accessibility best practices',
      'Portfolio of previous work',
    ],
    responsibilities: [
      'Build responsive web applications',
      'Collaborate with designers to implement UI/UX',
      'Optimize application performance',
      'Write clean, maintainable code',
      'Participate in design system development',
    ],
    salaryMin: 100000,
    salaryMax: 140000,
    salaryCurrency: 'USD',
    location: 'New York, NY',
    type: 'full-time',
    remote: true,
    experienceLevel: 'mid',
    postedDate: new Date('2024-11-05'),
    status: 'active',
  },
  {
    id: 'job-5',
    companyId: 'company-1',
    title: 'Data Scientist',
    description: 'Join our data team to build machine learning models and derive insights from large datasets.',
    requirements: [
      '3+ years of data science experience',
      'Strong Python and SQL skills',
      'Experience with machine learning frameworks',
      'Knowledge of statistical analysis',
    ],
    qualifications: [
      'Master\'s degree in relevant field',
      'Experience with big data technologies',
      'Strong communication skills',
    ],
    responsibilities: [
      'Build and deploy ML models',
      'Analyze complex datasets',
      'Present insights to stakeholders',
      'Collaborate with engineering teams',
    ],
    salaryMin: 130000,
    salaryMax: 170000,
    salaryCurrency: 'USD',
    location: 'San Francisco, CA',
    type: 'full-time',
    remote: true,
    experienceLevel: 'mid',
    postedDate: new Date('2024-11-03'),
    status: 'active',
  },
];

export const mockApplications: Application[] = [
  {
    id: 'app-1',
    jobId: 'job-1',
    candidateId: 'candidate-1',
    status: 'reviewing',
    appliedDate: new Date('2024-11-06'),
    coverLetter: 'I am excited to apply for the Senior Full Stack Engineer position. With over 8 years of experience...',
  },
  {
    id: 'app-2',
    jobId: 'job-2',
    candidateId: 'candidate-1',
    status: 'pending',
    appliedDate: new Date('2024-11-07'),
  },
  {
    id: 'app-3',
    jobId: 'job-3',
    candidateId: 'candidate-2',
    status: 'interview',
    appliedDate: new Date('2024-11-02'),
    coverLetter: 'As an experienced product manager with a proven track record in B2B SaaS...',
  },
];
